### ISSUE TITLE
Political Party Wheel Broken.

### ISSUE THREAD

**Issue by TNOLarper5** [Zakki0925224/tno-super-event-generator#1]
Hey I have an issue. The Political Party Popularity thing is Broken can you add that so It can be easier for people to Make ideology Wheels without it yk looking like it’s National Socialism when the idelogy is different. Please and thank you. Also allow others to use colors from TNO for their respective ideologies including Purple for Esoteric-Nazism/Agrarian Spartanism and Burgundian System. Thank you. Please reply when it’s been fixed.

**Comment by Zakki0925224** [comment]
Hello! I completely forgot to correct it. I have updated the political party popularity to change freely by CSS. Grammar is not that difficult, so I think it will be fine. Thank you for using it!
